### ISSUE TITLE
Add an issue template

### ISSUE THREAD

**Issue by cjihrig** [continuationlabs/celebrate#18]
Since https://github.com/continuationlabs/celebrate#issues exists, and is unlikely to be read by anyone opening an issue, maybe we should consider adding a GitHub issue template.

**Comment by arb** [comment]
Do you have a suggestion as to what it would look like? I guess the schema they are using and what else?

**Comment by cjihrig** [comment]
These are the ones used by Node - https://github.com/nodejs/node/tree/master/.github. I would suggest copying the existing text from the README, and also asking for OS, Node version, celebrate version, and if they are feeling spunky, the version of joi, since it's installed with loose patch and minor versions. I guess they could also include the problem that they're actually having :-P
