### ISSUE TITLE
Route params

### ISSUE THREAD

**Issue by ekoome** [continuationlabs/celebrate#28]
How do I use Celebrate to validate route params?

For example http://localhost/verify/12445

I need to validate 12445. How can I do this?

**Comment by cjihrig** [comment]
Check out the first example in the README. Instead of `body` or `query`, use `params`.

**Comment by ekoome** [comment]
Do I need to specify keys for Joi object? There is no key usually in params.

Secondly, if I would like to validate multiple parts of the route e.g /:user/:Id, how do I tell celebrate which parts of the route params I'm interested in.

An example to cover above scenario would help.

**Comment by cjihrig** [comment]
It works exactly like `body` and `query` in the README example. In your case, the keys would be named `user` and `id`.
