### ISSUE TITLE
Possible Enhancement

### ISSUE THREAD

**Issue by naveedn** [continuationlabs/celebrate#30]
Hey guys,

First of all, thank you very much for the repo you created. I have used Celebrate at the company I work at with great success, and it is used in production.

I recently built a library that exposes a fluent interface for Celebrate. You can find it here: https://github.com/naveedn/vayder

I built the library because the Express middleware pipeline lends itself to declaratively chaining validations, and the facade pattern makes it easy to understand what Celebrate is doing.

I was wondering if you guys were interested in having this interface directly incorporated in your repo? 

Thanks again!

**Comment by cjihrig** [comment]
I'm not entirely sure what you're proposing here. I think we're unlikely to add or remove anything from the interface. We want to keep this as a very thin layer on top of joi. Perhaps you could post some code showing the proposed APIs you'd be adding?

**Comment by naveedn** [comment]
Sorry if that wasn't clear. 

The library I created is a very thin layer on top of your library. All it does is provide a couple facade methods to make things easier to read.

It allows you to do stuff like:

```javascript
app.get('/',
  vayder.validateHeaders(AuthenticationSchema),
  vayder.validateQuery(paginationSchema),
  vayder.validateParams(userIdSchema),
  someController.doStuff);
```

I was wondering if you guys wanted that functionality directly inside celebrate. Otherwise I will keep it in my repo.

Cheers

**Comment by cjihrig** [comment]
I'm not sure what @arb thinks, but I think leaving the two modules/APIs separate makes sense.

**Comment by arb** [comment]
I agree with @cjihrig on this one. If you want to expose a wrapper like that, that's fine. That approach actually goes against one of the project goals of the project; being as close to hapi as reasonably possible.

**Comment by naveedn** [comment]
Understood, thanks for considering! Thanks again for your work.
