### ISSUE TITLE
Possible enhancement for @types

### ISSUE THREAD

**Issue by markmssd** [continuationlabs/celebrate#32]
I see there's already type definitions, which is awesome!
However, I don't understand why the schema has all 4 `params`, `headers`, `query`, and `body` set as required. Shouldn't they be set as optional, as such:
```
{
    params?: object,
    headers?: object,
    query?: object,
    body?: object,
}
```

For example, if I want to validate only the params, I shouldn't have to specify an empty `headers`, `query` and `body`.

Thanks for considering!

**Comment by arb** [comment]
You're right. PRs welcome 😄

**Comment by markmssd** [comment]
I'm not sure how to make at least one of them required, but I don't think it really matters. If someone wants to validate with `Celebrate({})`... why not :P I will try to PR tonight.

Also, another thing for TS users, would it be possible to import it as such:
```
import { Celebrate } from 'celebrate';
```

Currently the only way I found was:
```
import * as Celebrate from 'celebrate/lib';
```

No biggie, but definitely something worth enhancing :)
