### ISSUE TITLE
HTTP Status Code On Error

### ISSUE THREAD

**Issue by tommelo** [continuationlabs/celebrate#34]
Recently, I started using express with celebrate as a middleware for request body validation and there's a tiny detail that I'm wondering:

When a Joi constraint is violated, a response body is serialized and sent with a HTTP Status 400 (Bad Request). 

By [definition](https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status):

> 400 Bad Request
> This response means that server could not understand the request due to invalid syntax.

In this case, a bad request would be appropriated to a request body like:

```
// invalid JSON syntax
{ "param1": "abc", "param2": 
```

But, when the request body is well-formed, the server understands the content-type but cannot process the request due to business logic validation, should the default response be sent with a HTTP Status 422 (Unprocessable Entity)?

> 422 Unprocessable Entity
> The request was well-formed but was unable to be followed due to semantic errors.

**Comment by cjihrig** [comment]
I think 400 is more commonly used. I'd be open to making that code configurable. What do you think @arb?

**Comment by arb** [comment]
I was copying what hapi did which uses a 422. You can use your own error handler too... everything you need to create the same error message will be available and just use 400 instead. Would that be an acceptable solution?

**Comment by cjihrig** [comment]
Yea, I think the solution is to write the error handler to do it.

**Comment by tommelo** [comment]
The error handler then.
Thanks @cjihrig @arb
