### ISSUE TITLE
New joi versions available

### ISSUE THREAD

**Issue by cjihrig** [continuationlabs/celebrate#38]
Our `package.json` calls for joi 11.x.x.

joi 13.0.0 has been released.

**Comment by Marsup** [comment]
You don't necessarily need to bump this far, unless you also want to only support node 8.

**Comment by cjihrig** [comment]
What about joi 12.x.x?

**Comment by Marsup** [comment]
Still compat with node 4+.

**Comment by cjihrig** [comment]
celebrate should probably bump to joi 12 at least then. Thanks
