### ISSUE TITLE
how to extend joi schema

### ISSUE THREAD

**Issue by manjeettahkur** [continuationlabs/celebrate#53]
- `node` version - 8.0.0
- `celebrate` version - 6.0.0
- `joi` version (via `npm ls --depth=0 | grep joi`) - 12.x.x

My `joi` schema looks like this:

`  body: Joi.object().keys({
        request_id: Joi.string().required().options({ language: { any: { allowOnly: 'request id is required' }, label: 'request id' } }).label('please provide request id'),
        topic_name: Joi.string().required().options({ language: { any: { allowOnly: 'topic name is required' }, label: 'topic name' } }).label('The name of the topic is required'),
        additional_title: Joi.string().optional(),
        additional_search_tags: Joi.string().optional(),
        topic_level: Joi.string().optional(),
        parent_topic: Joi.array().sparse(),
        properties: Joi.object(),
        region: Joi.array().sparse(),
        published_start_date: Joi.date().optional(),
        published_end_date: Joi.date().optional()
    })  `

Here is an example value that is not working as expected:

`  body: Joi.object().keys({
        request_id: Joi.string().required().options({ language: { any: { allowOnly: 'request id is required' }, label: 'request id' } }).label('please provide request id'),
        topic_name: Joi.string().required().options({ language: { any: { allowOnly: 'topic name is required' }, label: 'topic name' } }).label('The name of the topic is required'),
        additional_title: Joi.string().optional(),
        additional_search_tags: Joi.string().optional(),
        topic_level: Joi.string().optional(),
        parent_topic: Joi.array().sparse(),
        properties: Joi.object(),
        region: Joi.array().sparse(),
        published_start_date: Joi.date().format('YYYY-MM-DD').optional(),
        published_end_date: Joi.date().format('YYYY-MM-DD').optional()
    })  `

The issue I am having with `celebrate` is: i am using joi-date-extensions to extend date format but show me this error "Cannot read property 'extend' of undefined
![screenshot from 2017-11-08 12 34 26](https://user-images.githubusercontent.com/14113726/32535698-3934e42e-c481-11e7-9539-1dbbe2b56110.png)
"
So Please let me know how i can solve this issue

**Comment by Marsup** [comment]
There is no mention of BaseJoi, just Joi, where did you get that one?

**Comment by manjeettahkur** [comment]
from here https://github.com/hapijs/joi-date-extensions

**Comment by Marsup** [comment]
This doesn't apply to how celebrate exposes joi, look at that project's readme.

**Comment by arb** [comment]
`BaseJoi` would be `undefined` in your example code. celebrate exports it as just `Joi`.

**Comment by manjeettahkur** [comment]
@arb So how I can extend my schema because extend method is not available.it is shown cannot read property of `extend` of undefined.

**Comment by Marsup** [comment]
If you want to keep it like in the screenshot, `const {Joi:BaseJoi} = celebrate`.

**Comment by manjeettahkur** [comment]
@Marsup  I am unable to `extend` method which us provided by joi.can u provide me, an example or you can try for yourself.

**Comment by Marsup** [comment]
I already gave you the exact line that needs to change for it to work. If it doesn't, provide a snippet that we can actually run locally.

**Comment by manjeettahkur** [comment]
Ok @Marsup  Let me check that one

**Comment by cjihrig** [comment]
I'm going to close this, as it doesn't seem like an issue with celebrate itself. Feel free to continue the conversation. If it turns out to be a celebrate bug, I'll reopen this.

**Comment by emanuelet** [comment]
that's how it appears to work for me
```
