### ISSUE TITLE
Unit testing validators

### ISSUE THREAD

**Issue by juliancoleman** [continuationlabs/celebrate#55]
- `node` version - 8.9.0
- `celebrate` version - ^7.0.1
- `joi` version (via `npm ls --depth=0 | grep joi`) -^13.0.2

Am I to be using `Joi.validate()`, or does `Celebrate` expose its own custom validator?

**Comment by giltho** [comment]
Celebrate exposes his own version of joi
So basically
```javascript
{ Joi } = require('celebrate');
Joi.validate(objectToValidate);
```
I am not entirely sure it answers to your question though

**Comment by juliancoleman** [comment]
Great. Thanks for the quick reply! That's all I needed to know.

**Comment by juliancoleman** [comment]
Perhaps that wasn't the solution. I'll outline my code below. What I'm trying to do is accomplish the same result as `Joi.validate(payload, validator);`

```js
// validator.js
const { celebrate, Joi } = require( 'celebrate' );

const Validator = celebrate( {
  params : Joi.object().keys( {
    eventKey : Joi.string().required(),
  } ).unknown( false ),
} );

module.exports = Validator;
```
```js
// validator_test.js
const { Joi } = require('celebrate');
const R = require('ramda');

const Validator = require('./validator');
const helpers = require('./helpers');

const validPayload = {
  params : {
    eventKey : 'testKey',
  },
};

describe('DeleteEventsValidator', () => {
  it(' does not allow unknown keys', () => {
    const payload = helpers.mergeObjectWithValidPayload(R.lensProp('params'), { unknownKey : 'hello' }, validPayload);
    const result = Joi.validate(payload, Validator);
    const { error } = result;

    expect(error).to.not.be.null;
    expect(R.prop('details', error)).to.have.length(1);

    expect(error.message).to.eql('"unknownKey" is not allowed');
  });
});
```

`helpers.mergeObjectWithValidPayload` is just a deep object merge. It will merge `{ unknownKey : 'hello' }` into `validPayload.params`.

Anyway, this throws the following error:

```
1) DeleteEventsValidator does not allow unknown keys:
   TypeError: Cannot read property 'params' of null
```

**Comment by giltho** [comment]
Hum, something is unclear with what you are doing
Celebrate is a middleware that should be used to validate inputs such as query/body/headers.
I don't see why you need to use Celebrate here, isn't Joi enough ?

`celebrate(...)`doesn't create a validator, it creates a middleware (a function that takes req, res and next)

Also, i don't know what tries to read the `params` property of your object but it might not be celebrate, I think the error comes from your call of `helpers.mergeObjectWithValidPayload`
(Although it does not change your question since it would have failed anyway because of your usage of celebrate

I realize this is not very clear, but you might want to try something more like :
```javascript
const Validator = Joi.object.keys( {
  params : Joi.object().keys( {
    eventKey : Joi.string().required(),
  } ).unknown( false ),
} );
```
And then use `Joi.validate` as you do

**Comment by juliancoleman** [comment]
I have no excuse for not figuring that out sooner. I apologize for the miscommunication. I thought Celebrate was a wrapper around Joi. Now I know! Thanks a bunch for another quick response. I've gotten my test passing now. I can continue with my work.

**Comment by giltho** [comment]
It sould be :)
Although depending on your version it might be `celebrate(Validator)` instead of `Celebrate(Validator)`
(I think there's a mistake in the readme on that point)

**Comment by giltho** [comment]
Wait that is not true, if you actually want to use Celebrate, the actual code would be :
```javascript
const Validator =  {
  params : Joi.object().keys( {
    eventKey : Joi.string().required(),
  } ).unknown( false ),
} ;

router.delete('/events/:eventKey', celebrate(validator), (req, res) => {
   // ...
});
```
`celebrate` takes an object with properties `params`, `headers` etc. (at least one of them), and each of these property should be a Joi schema.

**Comment by juliancoleman** [comment]
That is correct, yes
