### ISSUE TITLE
Custom Joi

### ISSUE THREAD

**Issue by eth0lo** [continuationlabs/celebrate#57]
The issue I am having with `celebrate` is:

I was wondering how I could use an extended Joi object with celetabre, the idea is that I could have custom validations.

**Comment by arb** [comment]
There is a test for this [here](https://github.com/continuationlabs/celebrate/blob/master/test/celebrate.test.js#L193-L226). Is that what you're trying to do?

**Comment by eth0lo** [comment]
Exactly that, but I was confused, by the recommendation of using the included Joi

**Comment by arb** [comment]
What is the confusion? You should use the bundled version of joi, and then extend it? I'm unclear what the confusion is.

**Comment by cjihrig** [comment]
The recommendation to use the bundled joi is to make sure there are not any compatibility issues. You are free to use whatever version of joi you want, and it **should** just work.

**Comment by eth0lo** [comment]
Perfect, thank you very much, feel free to close it
