### ISSUE TITLE
Force Validation

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [continuationlabs/celebrate#62]
I was watching a [Take Data Validation Seriously - Paul Milham, WildWorks](https://www.youtube.com/watch?v=3A73G5xntJI) and at [18:27](https://youtu.be/3A73G5xntJI?t=18m27s) he talks about the need for forced validation. 

Is there a way to force that the request goes through a Joi validation or the data isn't passed to the handler or there is a server error sent back?

Also, is this possible for response validation as well?

**Comment by ldesplat** [comment]
I did something similar where each of my routes in my application need to export a http method, uri, handler, and verification function which is just Celebrate.

My route schema
```
const routeSchema = Joi.object({
    method: Joi.string().required().valid('get', 'post', 'put', 'delete'),
    uri: Joi.string().min(4).required(),
    verify: Joi.func().required().allow(null),
    handler: Joi.func().required()
});
```

If the verify function is not present then I put in a middleware like this in front of the handler

```
const noRouteVerification = (req, res, next) => {
    delete req.body;
    delete req.query;
    return next();
};
```

So when I register all my routes I do something like this.
```
app[route.method](route.uri, route.verify ? route.verify : noRouteVerification, route.handler);
```

**Comment by BebeSparkelSparkel** [comment]
@ldesplat Thanks!

I'm wondering how I can add that with an express app without putting noRouteVerification in every route I create.
```javascript
  router.post('/create_customer',
    Celebrate({body: Joi.object().keys(validationSchema)}),  // validate data

    // strip data if not validated
    // but is hard to insert here and needs to be manually added
    noRouteVerification,

    (req, res) => {//handler function}
  )
```

I'm not sure how to always have this check without adding it manually before the handler for every route?

**Comment by ldesplat** [comment]
That's up to how you want to organize it. I personally call the router.post in a central place (as you see in my last code snipped) having exported an object full of routes. So I can detect when that happens.

For your use case, how you are using it right now, noRouteVerification will be really bad since it deletes the objects outright :D

I went about it a slightly different way that if my object which includes the route handler, does not have a verification then I will delete things and I assume that because there is some verification that it is exhaustive. You seem to want to ensure that Celebrate has gone and been run for every potential input.

If you want your use case, I would just create my own function that returns a Celebrate function with default configuration of body and query to be an object with no keys or something similar to that.

**Comment by BebeSparkelSparkel** [comment]
There has to be a way to modify the request object with an `app.use` in app.js

app.js
```javascript
const {ensureValidation} = require('./ensureValidation.js')

app.use(ensureValidation)
app.use('/', index)
```

index.js (express routes)
```javascript
const {celebrate} = require('../ensureValidation.js')

router.post('/create_customer',
  celebrate({body: Joi.object().keys(validationSchema)}),  // move data back to res.body/query/files
  (req, res) => {//handler function}
)
```

ensureValidation.js
```javascript
const celebrate = require('celebrate')

module.exports = {

  ensureValidation(req, res, next) {
    /* moves body, query, and files to another key until validated
    req.ensureValidation = {
      body: req.body,
      query: req.query,
      files: req.files,
    }

    req.body = req.query = req.files = 'Not yet validated'
  },

  celebrate(schema, [options]) {
    /* returns a celebrate wrapper that allows
        res.body, res.query, res.files to be accessed again */
    const cel_to_wrap = celebrate(schema, options)

    return (req, res, next) => {
      Object.assign(req, req.ensureValidation)
      delete ensureValidation

      cel_to_wrap(req, res, next)
    }
  }
```

I don't really like how if the user was very determined they could still access the data but it would make it very obvious that they were doing it incorrectly.

**Comment by cjihrig** [comment]
I'm going to close this because it's not really an issue with celebrate, but more how you organize an express app.
