### ISSUE TITLE
Log error/warning on Celebrate rejection

### ISSUE THREAD

**Issue by blackbetty** [continuationlabs/celebrate#63]
This is mostly a question, so the other stuff didn't seem relevant
The issue I am having with `celebrate` is:

I am looking for a simple way to log when Celebrate errors occur. I just started user testing linkmelater.win, and have a couple of users who are experiencing issues signing up. I think I know the root cause, but I want to confirm in my logs before I get back to them. Currently, celebrate just returns the 400 and a message describing what's missing. Since I don't have much user-defined input, I would like for that error message to just get logged  on my server too. any advice? Looking to avoid writing an error handler if I can (still pretty novice with Joi).

**Comment by cjihrig** [comment]
> Looking to avoid writing an error handler if I can

You need to write an Express error handling middleware. You can look at Celebrate's error handling middleware if you need inspiration - https://github.com/continuationlabs/celebrate/blob/99e525671eb93c1a6fa4f1f99a3fca6220c90909/lib/index.js#L101-L125.
