### ISSUE TITLE
Add Joi as a peer dependency

### ISSUE THREAD

**Issue by ramesius** [continuationlabs/celebrate#64]
For projects that install Joi as part of there own dependencies, it would be good to get warnings of incompatible versions when npm installing.

Edit: It looks like it used to be a peerDep but was removed at some point?

**Comment by cjihrig** [comment]
Yes, it was removed because peer dependencies are almost always a pain. Celebrate exposes the joi that it uses internally for maximum compatibility. However, you're free to use any version of joi you want. We just don't guarantee compatibility.

**Comment by ramesius** [comment]
Did a bit more reading and found exactly what you just mentioned in the readme 😅 . Thanks for the speedy response though. I can just install the exact version celebrate wants. 👍
