### ISSUE TITLE
celebrate undefined

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [continuationlabs/celebrate#66]
The docs show to require celebrate like below:
```javascript
// try-celebrate.js
const { celebrate, Joi, errors } = require('celebrate');
console.log('celebrate', celebrate);
```
terminal
```terminal
$ node try-celebrate.js 
celebrate undefined
```
but celebrate is undefined.  The below is what works for me to get the celebrate object:
```javascript
const celebrate = require('celebrate')
const { Joi, errors } = celebrate
console.log('celebrate', celebrate)
```

- `node` version - v8.5.0
- `celebrate` version - celebrate@6.0.1 
- `joi` version (via `npm ls --depth=0 | grep joi`) - joi@12.0.0

**Comment by arb** [comment]
If you're using an old version of `celebrate` (which you are) you need to check the tagged version of the read me [here](https://github.com/continuationlabs/celebrate/tree/v6.0.1)

**Comment by BebeSparkelSparkel** [comment]
`npm update celebrate` obviously not working
Thanks!
