### ISSUE TITLE
Send Back All Validation Errors

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [continuationlabs/celebrate#67]
celebrate seems to only send back one validation error at a time even if there are multiple validation errors.
Is it possible to have it validate all errors and then send back all of them?

**Comment by cjihrig** [comment]
You probably want to set the joi option [`abortEarly`](https://github.com/hapijs/joi/blob/master/API.md#validatevalue-schema-options-callback) to false. You can do that [here](https://github.com/continuationlabs/celebrate#celebrateschema-options).
